Repository dhruvdev01/huddle, pull requests merged in 2022-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#3 header-text-change
  index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#6 Tittle_update
  index.html
Labels: bug, help wanted, good first issue, hacktoberfest-accepted, hacktoberfest

#5 body-width-fix
  styles/style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#4 create style.css
  index.html
  styles/style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
